name: Build and Deploy to Surge
on:
  push:
    branches:
      - main  # Change this to your default branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you need
      - name: Install dependencies
        run: npm install
      - name: Build Expo app
        run: |
          npm install -g expo-cli
          expo build:web  # Build your Expo app for the web
      - name: Deploy to Surge
        run: |
          npm install -g surge
          surge login --token ${{ secrets.SURGE_TOKEN }}
          surge --project ./web-build --domain your-app.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}




