name: Build & Deploy
on:
  push:
    branches:
      - main
env:
  CI: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build Project
        run: npm run build:web
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./_static
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./_static
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Netlify Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.SURGE_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --prod --dir=./_static --site=$NETLIFY_SITE_ID
